#!/usr/bin/env python3
"""
Pre-rasterize a TTF font at a fixed pixel size into a C header
suitable for static linking. Output is two arrays + a struct
literal; see core/apps/ui/atlas.h for the C-side type definitions.

Run via tools/atlas_gen.sh which sets up the venv with Pillow.

Usage:
    atlas_gen.py <ttf-path> <pixel-size> <c-symbol-name> <output.h>

Example:
    atlas_gen.py tools/fonts-src/Nunito-Regular.ttf 13 NUNITO_REGULAR_13 \\
        core/apps/ui/atlas/nunito_regular_13.h
"""
import argparse
import os
import sys
from PIL import Image, ImageDraw, ImageFont

PRINTABLE = range(0x20, 0x7F)  # 0x20..0x7E inclusive — 95 glyphs


def render_atlas(ttf_path: str, px_size: int, symbol: str) -> str:
    font = ImageFont.truetype(ttf_path, px_size)
    ascent, descent = font.getmetrics()

    glyph_data = bytearray()
    glyphs = []   # list of (offset_x, offset_y, w, h, advance, data_offset)

    for codepoint in PRINTABLE:
        ch = chr(codepoint)
        bbox = font.getbbox(ch)  # (left, top, right, bottom) — top<0 = above baseline
        advance = int(round(font.getlength(ch)))

        if not bbox or (bbox[2] - bbox[0]) <= 0 or (bbox[3] - bbox[1]) <= 0:
            # Whitespace / no ink. Record an empty glyph with just an advance.
            glyphs.append((0, 0, 0, 0, advance, len(glyph_data)))
            continue

        offset_x = int(bbox[0])
        offset_y = int(bbox[1])  # negative for ascenders
        w = int(bbox[2] - bbox[0])
        h = int(bbox[3] - bbox[1])

        # Render onto a fresh L-mode image at glyph-bbox size. Origin
        # for ImageDraw.text is the pen baseline; we shift by -bbox to
        # land the visible ink at (0, 0) of the bitmap.
        img = Image.new("L", (w, h), 0)
        draw = ImageDraw.Draw(img)
        draw.text((-offset_x, -offset_y), ch, font=font, fill=255)
        bytes_ = img.tobytes()
        assert len(bytes_) == w * h, \
            f"unexpected byte count: {len(bytes_)} vs {w}*{h}"

        data_offset = len(glyph_data)
        glyph_data.extend(bytes_)
        glyphs.append((offset_x, offset_y, w, h, advance, data_offset))

    # Output as a C header.
    out = []
    out.append(f"// {symbol} — auto-generated by tools/atlas_gen.py.")
    out.append(f"// Source: {os.path.basename(ttf_path)} @ {px_size}px")
    out.append("// Edit the generator, not this file.")
    out.append("")
    out.append("#include \"../atlas.h\"")
    out.append("")
    out.append(f"static const uint8_t {symbol}_DATA[] = {{")
    # Pack 16 bytes per line for diff-friendliness.
    for i in range(0, len(glyph_data), 16):
        line = ", ".join(f"0x{b:02x}" for b in glyph_data[i:i + 16])
        out.append(f"    {line},")
    out.append("};")
    out.append("")
    out.append(f"static const atlas_glyph_t {symbol}_GLYPHS[95] = {{")
    for i, (ox, oy, w, h, adv, off) in enumerate(glyphs):
        cp = 0x20 + i
        out.append(
            f"    [{cp - 0x20:2d}] = {{ .data_offset = {off:5d}, "
            f".w = {w:3d}, .h = {h:3d}, "
            f".offset_x = {ox:3d}, .offset_y = {oy:3d}, "
            f".advance = {adv:3d} }},   // 0x{cp:02X} '{chr(cp) if cp != 0x5c else '\\'}'"
        )
    out.append("};")
    out.append("")
    # Line height: ascent + descent + a hair of leading.
    line_h = ascent + descent
    out.append(f"const atlas_t {symbol} = {{")
    out.append(f"    .glyphs      = {symbol}_GLYPHS,")
    out.append(f"    .data        = {symbol}_DATA,")
    out.append(f"    .ascent      = {ascent},")
    out.append(f"    .descent     = {descent},")
    out.append(f"    .line_height = {line_h},")
    out.append("};")
    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("ttf")
    ap.add_argument("px_size", type=int)
    ap.add_argument("symbol")
    ap.add_argument("output")
    args = ap.parse_args()

    contents = render_atlas(args.ttf, args.px_size, args.symbol)
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w") as f:
        f.write(contents)
    sys.stderr.write(f"wrote {args.output}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
